<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tenant Report</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; color: #111827; font-size: 12px; }
        h1 { font-size: 20px; margin: 0 0 4px; }
        h2 { font-size: 14px; margin: 18px 0 8px; }
        p { margin: 0 0 6px; color: #4b5563; }
        table { width: 100%; border-collapse: collapse; margin-top: 8px; }
        th, td { border: 1px solid #e5e7eb; padding: 8px; text-align: left; }
        th { background: #f9fafb; font-weight: 700; }
        .grid { width: 100%; margin-top: 10px; }
        .card { border: 1px solid #e5e7eb; border-radius: 8px; padding: 10px; margin-bottom: 8px; }
        .value { font-size: 18px; font-weight: 700; color: #111827; margin-top: 4px; }
    </style>
</head>
<body>
    <h1>{{ $tenantName }} - Reports & Analytics</h1>
    <p>Generated by: {{ $generatedBy }}</p>
    <p>Generated at: {{ $generatedAt->format('M d, Y h:i A') }}</p>

    <div class="grid">
        <div class="card">
            <strong>Revenue (paid payments)</strong>
            <div class="value">PHP {{ number_format($revenue ?? 0, 2) }}</div>
        </div>
        <div class="card">
            <strong>Damage Reports Logged</strong>
            <div class="value">{{ $damageCount ?? 0 }}</div>
        </div>
        <div class="card">
            <strong>Monthly Utilization ({{ $monthlyUtilization['period_label'] ?? now()->format('F Y') }})</strong>
            <div class="value">{{ $monthlyUtilization['reservation_total'] ?? 0 }} reservations</div>
            <p>Facilities used: {{ $monthlyUtilization['facility_usage_count'] ?? 0 }}</p>
        </div>
        <div class="card">
            <strong>Damage Charges Created</strong>
            <div class="value">{{ $damageChargeCount ?? 0 }}</div>
            <p>Pending damage payments: {{ $pendingDamagePayments ?? 0 }}</p>
        </div>
    </div>

    <h2>Most Reserved Facilities</h2>
    <table>
        <thead>
            <tr>
                <th>Facility</th>
                <th>Total Reservations</th>
            </tr>
        </thead>
        <tbody>
            @forelse($topFacilities as $facility)
                <tr>
                    <td>{{ $facility->name }}</td>
                    <td>{{ $facility->reservations_count }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="2">No data yet.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <h2>Peak Days</h2>
    <table>
        <thead>
            <tr>
                <th>Day</th>
                <th>Total Reservations</th>
            </tr>
        </thead>
        <tbody>
            @forelse($peakDays as $row)
                <tr>
                    <td>{{ $row->day_name }}</td>
                    <td>{{ $row->total }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="2">No data yet.</td>
                </tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>
